### ISSUE TITLE
请问数据文件有吗

### ISSUE THREAD

**Issue by JimJim2090** [LLouice/Sohu2019#1]
news.pkl这些文件有吗？给部分也可以，多谢！

**Comment by LLouice** [comment]
这些生成的文件都特别大，而且都已经从服务器上删除了。
如果你有需要的话可以从 [2019 搜狐校园算法大赛](https://biendata.com/competition/sohu2019/data/)下载原始数据，然后自己生成

**Comment by macanv** [comment]
大佬，rank多少啊

**Comment by ladybirdhui** [comment]
你好 不知道能不能分享一下数据集，官方网站已经不允许下了，谢谢
