### ISSUE TITLE
想问下 最后分数是多少呀..

### ISSUE THREAD

**Issue by xuanzebi** [LLouice/Sohu2019#2]
顺便问下是多少名呀

**Comment by LLouice** [comment]
怎么都问这个让人尴尬的问题:anguished: 
最后F1为0.563，排第七
另外，拜访了同学你的主页和博客:thumbsup: 好奇你们难道看不了终榜吗？

**Comment by xuanzebi** [comment]
主要是最近有任务要做一下关键词（实体）抽取..所以分数高的话就打算参考参考hhh
挺棒的啦 大佬.. 
PS...我是菜鸡..
