### ISSUE TITLE
有关pytorch-transformers 也就是之前的pytorch-pretrained-BERT问题

### ISSUE THREAD

**Issue by ladybirdhui** [LLouice/Sohu2019#3]
你好 ，我想问问 在pytorch版本的bert中，关于中文文本的词向量是否只是字向量，因为我是用Tokenizer 进行转换尝试，发现只对字有作用，一个词，比如“学校”，会转换成两个token-id

不知道你在使用的时候是否也是这样的，如果真是这样，那是否会对结果产生影响，毕竟只是一个个字向量

**Comment by LLouice** [comment]
相关的api有参数选项可选是输出字向量(默认）还是词向量(好像就是CLS的值)，你可以查阅一下源代码的参数。注：这里的常用场景就是纯粹将bert当成了词向量提取器
做命名实体识别的话本身就是基于字的序列标注任务，而且在不同语句中“学校”的token向量(token-id相同，但经过bert得到的向量）是不同的，bert加入了上下文信息，所以对结果没有影响

**Comment by ladybirdhui** [comment]
谢谢 懂了
